Repository rhyperio/studienarbeit_code, pull requests merged in 2023-03, with the labels that each got.

#4 Generate typ-2-grammar via probability
  .gitignore
  pom.xml
  src/main/java/de/dhbw/karlsruhe/grammar/generation/GrammarGeneration.java
  src/main/java/de/dhbw/karlsruhe/grammar/generation/GrammarProbabilityGeneration.java
  src/main/java/de/dhbw/karlsruhe/models/Grammar.java
  src/test/java/de/dhbw/karlsruhe/grammar/generation/GrammarProbabilityGenerationTest.java
Labels: implementation

#7 Added Spring-Boot support and Swagger-API
  Readme.md
  pom.xml
  src/main/java/de/dhbw/karlsruhe/App.java
  src/main/java/de/dhbw/karlsruhe/ServletInitializer.java
  src/main/java/de/dhbw/karlsruhe/config/SpringdocConfig.java
  src/main/java/de/dhbw/karlsruhe/controller/DerivationTreeController.java
  src/main/java/de/dhbw/karlsruhe/controller/dto/ValidationTreeParamModel.java
  src/main/java/de/dhbw/karlsruhe/derivation/tree/validation/DerivationTreeValidation.java
  src/main/java/de/dhbw/karlsruhe/security/APIKeyAuthFilter.java
  src/main/java/de/dhbw/karlsruhe/security/SecurityConfig.java
  src/main/java/de/dhbw/karlsruhe/services/GrammarService.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#5 Grammar generation via concatenation of terminals and non terminals
  src/main/java/de/dhbw/karlsruhe/grammar/generation/GrammarConcatenationGeneration.java
  src/main/java/de/dhbw/karlsruhe/grammar/generation/GrammarConcatenationVerification.java
  src/main/java/de/dhbw/karlsruhe/models/Grammar.java
  src/test/java/de/dhbw/karlsruhe/grammar/generation/GrammarConcatenationGenerationTest.java
Labels: implementation

#8 Top down validation fix
  src/main/java/de/dhbw/karlsruhe/top/down/parsing/validation/TopDownAcceptorValidation.java
  src/test/java/de/dhbw/karlsruhe/top/down/parsing/TopDownAcceptorValidationTest.java
  src/test/resources/top_down_parsing/TopDownWrongGrammarUsage.json
Labels: improvement

#13 Derivation tree result
  src/main/java/de/dhbw/karlsruhe/controller/DerivationTreeController.java
  src/main/java/de/dhbw/karlsruhe/derivation/tree/models/DetailResult.java
  src/main/java/de/dhbw/karlsruhe/derivation/tree/validation/DerivationTreeValidation.java
  src/test/java/de/dhbw/karlsruhe/derivation/tree/DerivationTreeValidationTest.java
Labels: enhancement
